repos:
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      language_version: python3.9
      args: [--line-length=120]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
    - id: hadolint
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.2
  hooks:
    - id: terraform_tflint
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: no-commit-to-branch
      args: [--branch, main]
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-ast
    - id: check-toml
    - id: debug-statements
    - id: detect-private-key
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      args:
        - --max-line-length=120
