FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/ .

ARG DEBUG_MODE
ENV DEBUG_MODE=$DEBUG_MODE
ARG POST_URL
ENV POST_URL=$POST_URL

# Make the start script executable
RUN chmod +x ./start_frontend.sh

CMD ["./start_frontend.sh"]
