FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/ .

ARG DEBUG_MODE
ENV DEBUG_MODE=$DEBUG_MODE

CMD ["python", "frontend.py"]
