name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: gptunes_dev
  IMAGE_NAME: gptunes_backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME .
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME

      - name: Configure gcloud
        run: gcloud config set project ${{ env.PROJECT_ID }}

      - name: Configure Docker credential helper for Artifact Registry
        run: gcloud auth configure-docker gcr.io

      - name: Tag Docker image for Artifact Registry
        run: docker tag gcr.io/$PROJECT_ID/$IMAGE_NAME gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}

      - name: Push Docker image to Artifact Registry
        run: docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}
