name: Push Docker image to GCP Artifact Registry

on:
  push:
    branches:
      - dev
      - main

env:
  REPO_NAME: gptunes-backend
  IMAGE_NAME: gptunes-backend
  REGION: europe-west4

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: Set ENV_ID and PROJECT_ID based on branch
        id: set_vars
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "::set-output name=env_id::${{ secrets.PROD_ENV_ID }}"
            echo "::set-output name=project_id::gptunes"
          else
            echo "::set-output name=env_id::${{ secrets.DEV_ENV_ID }}"
            echo "::set-output name=project_id::gptunes-dev"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            europe-west4-docker.pkg.dev/${{ steps.set_vars.outputs.project_id }}/gptunes-backend/gptunes-backend:${{ github.sha }}
          build-args: |
            ENV_ID=${{ env.ENV_ID }}
