name: Push Docker image to GCP Artifact Registry

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: gptunes-dev
  REPO_NAME: gptunes-backend
  IMAGE_NAME: gptunes-backend
  REGION: europe-west4

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west4-docker.pkg.dev/gptunes-dev/gptunes-backend/

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            europe-west4-docker.pkg.dev/gptunes-dev/gptunes-backend/gptunes-backend:${{ github.sha }}
            europe-west4-docker.pkg.dev/gptunes-dev/gptunes-backend/gptunes-backend:latest
