name: Set up GCP infrastructure with Terraform

on:
  push:
    branches:
      - dev
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change to Terraform directory
        run: cd infra/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_image_tag: ${{ github.sha }}
