name: Set up GCP infrastructure with Terraform

on:
  push:
    branches:
      - dev
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Terraform Init
        run: terraform init
        working-directory: infra/

      - name: Terraform Apply
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            VAR_FILE="envs/main/config.tfvars"
          else
            VAR_FILE="envs/dev/config.tfvars"
          fi
          terraform apply -auto-approve -var-file="$VAR_FILE"
        working-directory: infra/
        env:
          TF_VAR_image_tag: ${{ github.sha }}
